const products = [
  {
    id: 1,
    first_name: 'Dore',
    last_name: "O'Lennachain",
    email: 'dolennachain0@loc.gov',
    gender: 'Female',
    ip_address: '34.69.100.220',
    image: 'http://dummyimage.com/1617x948.png/dddddd/000000',
    job: 'Compensation Analyst',
    price: 41,
  },
  {
    id: 2,
    first_name: 'Jolyn',
    last_name: 'Checchi',
    email: 'jchecchi1@drupal.org',
    gender: 'Genderfluid',
    ip_address: '57.161.249.205',
    image: 'http://dummyimage.com/1426x850.png/5fa2dd/ffffff',
    job: 'Desktop Support Technician',
    price: 76,
  },
  {
    id: 3,
    first_name: 'Caye',
    last_name: 'Clardge',
    email: 'cclardge2@fc2.com',
    gender: 'Female',
    ip_address: '232.205.16.120',
    image: 'http://dummyimage.com/1380x840.png/5fa2dd/ffffff',
    job: 'Software Consultant',
    price: 89,
  },
  {
    id: 4,
    first_name: 'Natividad',
    last_name: 'Cerro',
    email: 'ncerro3@discuz.net',
    gender: 'Genderqueer',
    ip_address: '20.114.45.114',
    image: 'http://dummyimage.com/1875x841.png/5fa2dd/ffffff',
    job: 'Help Desk Operator',
    price: 47,
  },
  {
    id: 5,
    first_name: 'Neysa',
    last_name: 'Nehls',
    email: 'nnehls4@toplist.cz',
    gender: 'Agender',
    ip_address: '156.41.254.201',
    image: 'http://dummyimage.com/1365x911.png/5fa2dd/ffffff',
    job: 'Account Representative IV',
    price: 79,
  },
  {
    id: 6,
    first_name: 'Jocelin',
    last_name: 'Lumby',
    email: 'jlumby5@wikimedia.org',
    gender: 'Genderfluid',
    ip_address: '243.227.75.51',
    image: 'http://dummyimage.com/1461x951.png/5fa2dd/ffffff',
    job: 'Marketing Assistant',
    price: 64,
  },
  {
    id: 7,
    first_name: 'Hatty',
    last_name: 'Cord',
    email: 'hcord6@google.cn',
    gender: 'Female',
    ip_address: '88.195.196.22',
    image: 'http://dummyimage.com/1375x805.png/5fa2dd/ffffff',
    job: 'Senior Cost Accountant',
    price: 65,
  },
  {
    id: 8,
    first_name: 'Ralph',
    last_name: 'Downing',
    email: 'rdowning7@bbc.co.uk',
    gender: 'Genderfluid',
    ip_address: '43.5.193.28',
    image: 'http://dummyimage.com/1904x851.png/cc0000/ffffff',
    job: 'VP Quality Control',
    price: 58,
  },
  {
    id: 9,
    first_name: 'Bentlee',
    last_name: 'Bodycote',
    email: 'bbodycote8@bloomberg.com',
    gender: 'Non-binary',
    ip_address: '132.119.39.37',
    image: 'http://dummyimage.com/1497x971.png/cc0000/ffffff',
    job: 'Technical Writer',
    price: 68,
  },
  {
    id: 10,
    first_name: 'Vivianne',
    last_name: 'Chominski',
    email: 'vchominski9@japanpost.jp',
    gender: 'Polygender',
    ip_address: '82.206.52.110',
    image: 'http://dummyimage.com/1808x868.png/dddddd/000000',
    job: 'VP Product Management',
    price: 23,
  },
]

export default products
