export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_REMOVE_ALL_ITEMS = 'CART_REMOVE_ALL_ITEMS'
 
export const SAVE_SHIPPING_INFO_SUCCESS = 'SAVE_SHIPPING_INFO_SUCCESS' 
export const SAVE_PAYMENT_METHOD_SUCCESS = 'SAVE_PAYMENT_METHOD_SUCCESS'