export const GAME_LIST_REQUEST = 'GAME_LIST_REQUEST'
export const GAME_LIST_SUCCESS = 'GAME_LIST_SUCCESS'
export const GAME_LIST_FAIL = 'GAME_LIST_FAIL'

export const GAME_DETAILS_REQUEST = 'GAME_DETAILS_REQUEST'
export const GAME_DETAILS_SUCCESS = 'GAME_DETAILS_SUCCESS'
export const GAME_DETAILS_FAIL = 'GAME_DETAILS_FAIL'

export const LIST_GAME_FILTER_REQUEST = 'LIST_GAME_FILTER_REQUEST'
export const LIST_GAME_FILTER_SUCCESS = 'LIST_GAME_FILTER_SUCCESS'
export const LIST_GAME_FILTER_FAIL = 'LIST_GAME_FILTER_FAIL'

export const UPLOAD_GAME_REQUEST = 'UPLOAD_GAME_REQUEST'
export const UPLOAD_GAME_SUCCESS = 'UPLOAD_GAME_SUCCESS'
export const UPLOAD_GAME_FAIL = 'UPLOAD_GAME_FAIL'