export const GAME_LIST_REQUEST = 'GAME_LIST_REQUEST'
export const GAME_LIST_SUCCESS = 'GAME_LIST_SUCCESS'
export const GAME_LIST_FAIL = 'GAME_LIST_FAIL'

export const GAME_DETAILS_REQUEST = 'GAME_DETAILS_REQUEST'
export const GAME_DETAILS_SUCCESS = 'GAME_DETAILS_SUCCESS'
export const GAME_DETAILS_FAIL = 'GAME_DETAILS_FAIL'