export const ORDER_PLACE_REQUEST = 'ORDER_PLACE_REQUEST' 
export const ORDER_PLACE_SUCCESS = 'ORDER_PLACE_SUCCESS' 
export const ORDER_PLACE_FAIL = 'ORDER_PLACE_FAIL' 

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST' 
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS' 
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL' 